<?php

namespace BOBeatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeatRepository extends EntityRepository
{
}
