bo_user:
    resource: "@BOUserBundle/Controller/"
    type:     annotation
    prefix:   /

bo_beat:
    resource: "@BOBeatBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: BOUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:    /logout
